### ISSUE TITLE
Stuff to do

### ISSUE THREAD

**Issue by drummyfish** [OpenMafia/OpenMF-Archived#44]
Small things anyone can pick up and fix. Larger tasks are to be discussed elsewhere.

- [x] figure out and fix why the door in 00MENU mission is weirdly scaled (probably related to other model misplacements, like ~~traffic lights~~)
- [x] implement transparency maps
- [x] figure out and fix why lighting changes sometimes when camera moves
- [x] figure out which files in DTA are compressed and what compression is used
- [ ] figure out how to set the lights from scene2.bin to match the Mafia look and how to get around the OSG 8 lights limit (use [this](http://osg-users.openscenegraph.narkive.com/6lcD3b3n/many-lights-in-osg-solution)?)
- [ ] implement debug text labels in the scene
- [x] find out how to do and implement [mesh flattening](https://www.panda3d.org/reference/1.9.1/python/panda3d.core.NodePath#a468760715b15dd5c67e086bafcf3602b) in OSG
- [x] set up the OSG profiler
- [x] filter out unnecessary light types when loading scene2.bin
- [x] optimize OSG loading (create fewer nodes when possible, make instances, ...) ([help](https://github.com/drummyfish/osgdebug))
- [x] turn on distance fog
- [ ] `grep -rnw "TODO\|FIXME" ./components/ ./apps/`
- [ ] refactor
- [x] extract DTA decrypting keys from the dll/exe instead of having them in the source (let's make sure we don't get sued)
- [x] implement environment mapping (reflections)
- [x] implement one-sided/double-sided material flag
- [x] implement billboards
- [x] create reference screenshots (and videos?) from vanilla engine - menu, various missions, models - and make them easily accessible (e.g. imgur) - https://imgur.com/a/5B5R4 (always can use more though)
- [ ] load and apply light maps
- [x] load models AND textures via some manager that will hand back already loaded resources, to not waste memory by loading same texture twice for different models etc.
- [x] handle remaining mesh types in 4ds osg loader
- [x] find out why certain things (usually colorkey transparent: see guardrails by the roads, the big bridge, ...) have weird geometry/texture mapping and apply a fix
- [ ] find out what default material means (material ID = 0) in the context of 4ds loading and apply the knowledge
- [x] implement animated textures
- [x] improve logger class to be able to hide certain kinds of messages (info, warn, ...), to include optional caller string and so allow for filtering by caller etc.
- [x] create a nice doxyfile
- [x] fix near/far plane setting not working in OSG renderer
- [x] find out and fix why skybox edges are slightly visible
- [x] apply global light when viewing a single model in viewer
- [x] play around with osg::CullSettings to achieve better performance (small feature culling etc.)
- [x] refactor DTA parser (names, content => table etc.) and incorporate info from [H&D wiki](http://hd2.wikia.com/wiki/DTA) and mainly the new info from ASM
- [x] find the bug in LZSS decompression in DTA module and fix it
- [x] implement the rest of DTA loading
- [ ] find out what exactly mScale2 field in cache.bin means, and implement it
- [x] fix culling issues with transparent occluders (e.g. freekrajina, fake reflections under the bridge are sometimes culled even though visible)
- [x] find out when to use mPos vs mPos2 in scene.bin
- [ ] ~~implement~~ improve MATERIALFLAG_ADDITIVEMIXING (streetlights)
- [ ] implement particle systems
- [ ] start making automated tests
- [ ] create a superclass for .bin formats
- [x] find out what the heck is that giant thing in tutorial mission, and get rid of it
- [ ] in 00menu, figure out why the "light ray object" from the projector isn't visible, and fix it
- [ ] find a mesh of type MIRROR somewhere in the game (EDIT: one is in mise11-vila, bedroom on second floor), and ideally make it work
- [ ] find out why skybox is messed up in the mission mise11-vila, and fix it
- [x] find out why in mise11-vila furniture is wrongly rotated, and fix
- [ ] figure out details on how 5DS animations work, document and implement the basics
- [x] improve tree.klz format parser/util so that we can begin working out collisions
- [ ] write parsers for remaining formats (road.bin, effects.bin, car_table.dat, check.bin, ...)
- [ ] start writing a basic mafiascript parser/interpreter and scripts to test it with (we can't upload mafia's scripts into the repo as we don't own them)
- [ ] figure out details about GLOW mesh type and implement it
- [x] fix "_LARGEFILE64_SOURCE" redefined" warning in zpl
- [x] generalize loader_cache to be able to store also non-OSG objects, like DataFormat objects
- [ ] fix segfaults when exporting scene to file
- [ ] figure out why in 00menu, some items are slightly incorrectly transformed (photo has wrong scale, keys have incorrect rotation, wallpapers are wrong, ...), and fix
- [x] separate renderer and input event handling
- [x] implement 3D object picking for debugging
- [ ] make public domain content for automated testing (4DS models, DTA files, simple missions, ...)
- [x] implement [fixed update time step, variable rendering](http://gameprogrammingpatterns.com/game-loop.html) game loop
- [x] implement loading the rest of collision shapes from tree.klz to Bullet
- [ ] find out about acceleration structures for static collision geometry and add it (btDbvtBroadphase,  btAxisSweep3, as said [here](http://www.bulletphysics.org/mediawiki-1.5.8/index.php?title=Collision_Callbacks_and_Triggers#contactTest))
- [x] make use of better entity ID allocation system
- [ ] find out/fix why collisions with cylinders sometimes don't register
- [x] implement --no-treeklz flag for viewer (so that the scene can be exported without collision shapes)
- [ ] add search functionality to viewer (e.g. `--find name` parametr that will find an entity with given name, debug select it and center camera on it)
- [x] make a simple linear algebra module with vector/matrix math to get rid of multiple implementations of Vec3, Mat4 (DataFormat::Vec3, MFGame::Vec3, ...) etc.
- [x] use cache loader to store/load parsed files (e.g. scene.4ds parsed from withing OSG loader doesn't have to be parsed again by Bullet loader etc.)
- [x] fix the "viewer flickering"
- [x] apply world transform to face collision rigid bodies in bullet loader (**not** elsewhere)
- [ ] fix zpl warning spam
- [ ] apply scale to klz collision shapes (one example is in the tutorial map, car bumps at the playground)
- [x] find out whether tree.klz can contain links to meshes loaded from other files than scene.4ds (it seems like there are links to objects from scene2.bin of format "objectname.meshname"), and possibly implement that
- [ ] create a compile-time option to not create debug OSG nodes for the release version to save memory
- [ ] make the debug 3D picker print out the node associated visual entity
- [x] create a factory for spatial entities
- [x] fix entity visual/physics matching (e.g. freeride - bins in the street aren't matched)
- [x] add physics to OSG profiler (see how it's done in OpenMW)
- [ ] try out different allocation strategy for spatial entities
- [x] add CMake option to select the executables to be compiled, to make compiling faster
- [x] fix profiler broken after input manager addition
- [ ] find out why btDbvtBroadphase physics algorithm always ignores the first collision and only registers the following ones
- [ ] find out/fix why on some platforms (Linux) camera collisions (point collision) doesn't work sometimes (seems like -P parameter makes it not work)
- [ ] fix segfault that sometimes happens when quitting viewer (shared_ptr probably frees already freed rigid body, use valgrind)
- [ ] implement entity/player smooth turn (as opposed to instant turn)
- [ ] address the issue of files being loaded directly to structs, which may break different-endian system compatibility (ARM, ...)
- [ ] try to separate the math util library into .hpp and .cpp (currently header-only, makes recompile everything on any change)
- [ ] make Dear ImGUI work with OSG renderer
- [ ] deal with memory leak in 4DS OSG loader

**Comment by volca02** [comment]
A sort of cosmetic proposal - I encountered an issue while setting things up. The unpacking tool I used (Mafia DTA Extractor, ran in wine) produced filenames with upper case letters. This caused the viewer to silently fail...

[ ] There could be some info about this in the development.md
[ ] Failed loads of data should be reported in console - generally any kind of error encountered
[ ] Loggers seem to use ineffective string concatenation - stuff like libfmt could be used instead, maybe? (https://github.com/fmtlib/fmt)

**Comment by zaklaus** [comment]
I believe zpl can be used to format strings (or even print them) as well, without a hassle. The library is supposed to offer faster alternatives to std libraries and that's what we delivered. zpl is located in the extern/ folder.

**Comment by drummyfish** [comment]
Oh yes, we forgot to mention extracted files have to be lowercase - our extractor does it but DTA extractor doesn't, gotta fix it.

**Comment by volca02** [comment]
About that - I hit a roadblock whilst using the provided dta extractor which the linked one did not have problems with. The merge request I did changed the behavior to fail by exception instead of SEGV, but the problem remains. - Shall I create a separate issue for that, or is it a known thing?

**Comment by drummyfish** [comment]
Yes, maybe create a new issue, the DTA extractor isn't well tested, we know there are bugs but they're not documented.
