### ISSUE TITLE
Extra features against the original game

### ISSUE THREAD

**Issue by drummyfish** [OpenMafia/OpenMF-Archived#93]
More of a motivational list at this stage. Add stuff you'd like to see added as extra features against the original game.

- [ ] multiplayer
- [ ] ragdoll physics for people
- [ ] improved graphics (postprocessing, shadows, env. mapping generation, water shader, ...)
- [ ] save game at any time
- [ ] scripting in other languages than MafiaScript (Lua, Python, ...)
- [ ] interactive ingame console, real-time scripting
- [ ] additional content format support
- [ ] more camera settings (first person, over the shoulder, variable distance, FOV, ...)
- [ ] 360 degree screenshots, 3D screenshots
- [ ] all-in-one ultimate content editor
- [ ] swimming
- [ ] support for planes and boats
- [ ] replays
- [ ] mod format (save only diffs against the original) and manager

**Comment by L33TM4S73R** [comment]
How about a way to load external .dnc files instead of adding them to a scene2.bin?
